### ISSUE TITLE
Potential communication request

### ISSUE THREAD

**Issue by ericzzj1989** [Martin0Li/oriented_detection#1]
Hello, I notice the question proposed by you in SiLK repo [here](https://github.com/facebookresearch/silk/issues/8)
My research interests include feature detection/description/matching, visual localization, vSLAM and I am currently doing the wide baseline image matching problem.
I wonder if you are doing research on topics about image matching/local feature/pose estimation. If so, would you mind if we had further communication?

**Comment by Martin0Li** [comment]
yes,sure.

**Comment by ericzzj1989** [comment]
> 

Do you have Wechat?

**Comment by Martin0Li** [comment]
This is my WeChat ID:-MarTinMT-.

**Comment by Crazylov3** [comment]
Hi,
I am also working on topics about image matching/local feature/pose estimation. I really want to join. Do you have any global social platforms like Discord or Telegram? I can't create WeChat account

**Comment by ericzzj1989** [comment]
> Hi, I am also working on topics about image matching/local feature/pose estimation. I really want to join. Do you have any global social platforms like Discord or Telegram? I can't create WeChat account

Do you have WhatsApp?

**Comment by Crazylov3** [comment]
@ericzzj1989 Yes, my WhatsApp number is +84348157809
